import { createFileRoute } from "@tanstack/react-router";
import { absoluteUrl } from "@/lib/site";

export const Route = createFileRoute("/robots.txt")({
  server: {
    handlers: {
      GET: () => new Response(
        [
          "User-agent: *",
          "Allow: /",
          "",
          "User-agent: Googlebot",
          "Allow: /",
          "",
          "User-agent: Bingbot",
          "Allow: /",
          "",
          "User-agent: GPTBot",
          "Allow: /",
          "",
          "User-agent: ClaudeBot",
          "Allow: /",
          "",
          "User-agent: PerplexityBot",
          "Allow: /",
          "",
          "User-agent: Google-Extended",
          "Allow: /",
          "",
          "User-agent: OAI-SearchBot",
          "Allow: /",
          "",
          "User-agent: ChatGPT-User",
          "Allow: /",
          "",
          "User-agent: anthropic-ai",
          "Allow: /",
          "",
          "User-agent: Claude-Web",
          "Allow: /",
          "",
          "User-agent: Perplexity-User",
          "Allow: /",
          "",
          "User-agent: Applebot",
          "Allow: /",
          "",
          "User-agent: Applebot-Extended",
          "Allow: /",
          "",
          "User-agent: CCBot",
          "Allow: /",
          "",
          "User-agent: Bytespider",
          "Allow: /",
          "",
          "User-agent: Amazonbot",
          "Allow: /",
          "",
          "User-agent: DuckDuckBot",
          "Allow: /",
          "",
          "User-agent: YandexBot",
          "Allow: /",
          "",
          "User-agent: meta-externalagent",
          "Allow: /",
          "",
          `Sitemap: ${absoluteUrl("/sitemap.xml")}`,
          "",
        ].join("\n"),
        { headers: { "Content-Type": "text/plain; charset=utf-8", "Cache-Control": "public, max-age=3600" } },
      ),
    },
  },
});
