import { ArrowRight, Image, Music2, Scissors, Sparkles, Subtitles, Wand2 } from "lucide-react";
import { Link } from "@tanstack/react-router";
import { MarketingLayout, SectionTitle } from "@/components/SiteChrome";
import { MostPopularBlogs } from "@/components/MostPopularBlogs";

const features = [
  [Scissors, "Script-driven editing", "Your images or videos should match the corresponding voiceover/script lines, so the scenes stay in the correct position."],
  [Sparkles, "Automatic motion", "Turn still images into subtle motion so your videos can feel polished instead of frozen."],
  [Wand2, "Transitions & motion graphics", "Choose Mixed, Smooth, Dynamic or Minimal transitions and add scene-level graphics such as Lower Third, Text Callout, Date Stamp, Location Pin and Quote Card."],
  [Subtitles, "Auto Captions", "Choose caption settings and styles according to your needs and the style of your video."],
  [Music2, "Voiceover & audio", "Use background music, auto-duck music under voiceover, trim leading/trailing silence, normalize loudness, boost voice clarity and control fades."],
  [Image, "Color & export", "Choose None, Cinematic, Warm, Cool, Vintage or Vivid color grades, fine-tune the image and export in 720p, 1080p or 4K."],
] as const;

export function HomePageWithPopular() {
  return <MarketingLayout>
    <section className="relative overflow-hidden border-b border-zinc-800"><div className="absolute inset-0 bg-[radial-gradient(circle_at_50%_-20%,rgba(245,158,11,.18),transparent_50%)]" /><div className="relative mx-auto max-w-6xl px-4 pb-24 pt-20 text-center sm:px-6 sm:pt-28"><span className="inline-flex rounded-full border border-amber-500/20 bg-amber-500/10 px-3 py-1 text-xs font-semibold text-amber-300">Automatic video editing for creators</span><h1 className="mx-auto mt-6 max-w-4xl text-5xl font-black tracking-tight text-white sm:text-7xl">Edit your videos in just a few minutes.</h1><p className="mx-auto mt-6 max-w-2xl text-lg leading-8 text-zinc-400 sm:text-xl">Our main purpose is to provide convenience with the help of AI. Upload your media, voiceover and required data, then let Auto Edit automatically edit and arrange your video.</p><div className="mt-9 flex flex-col justify-center gap-3 sm:flex-row"><Link to="/editor" className="inline-flex items-center justify-center gap-2 rounded-xl bg-amber-500 px-6 py-3.5 font-bold text-zinc-950 hover:bg-amber-400">Open the editor <ArrowRight className="h-5 w-5" /></Link><Link to="/how-it-works" className="inline-flex items-center justify-center rounded-xl border border-zinc-700 px-6 py-3.5 font-semibold text-white hover:bg-zinc-900">See how it works</Link></div><div className="mx-auto mt-14 grid max-w-3xl grid-cols-1 gap-3 text-left sm:grid-cols-3"><Stat title="Save time" text="Complete hours of video editing work in just a few minutes" /><Stat title="4 ratios" text="16:9, 9:16, 1:1, 4:5" /><Stat title="4K export" text="High-quality video result" /></div></div></section>
    <section className="mx-auto max-w-6xl px-4 py-20 sm:px-6"><SectionTitle eyebrow="Built for creators" title="Everything you need for a professional video" description="The tool is designed to be easy enough for people of different ages and experience levels to use." /><div className="mt-12 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{features.map(([Icon,title,text])=><FeatureCard key={title} Icon={Icon} title={title} text={text} />)}</div></section>
    <section className="border-y border-zinc-800 bg-zinc-900/40"><div className="mx-auto grid max-w-6xl gap-12 px-4 py-20 sm:px-6 lg:grid-cols-2 lg:items-center"><div><p className="text-sm font-semibold uppercase tracking-[.18em] text-amber-400">Simple workflow</p><h2 className="mt-3 text-3xl font-bold text-white sm:text-4xl">Instead of spending valuable time on video editing.</h2><p className="mt-5 text-zinc-400 leading-7">You can use that time for something more productive and meaningful. Follow the simple workflow and let the tool handle the repetitive editing work.</p><div className="mt-7 grid gap-4">{['Upload your media in the correct Scene 1, Scene 2 sequence','Upload your original voiceover and optional background music','Provide your original script and Word Timestamp Transcript','Preview your video, configure settings and export'].map((x,i)=><div key={x} className="flex gap-3"><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-amber-500 text-sm font-bold text-zinc-950">{i+1}</span><span className="pt-1 text-sm text-zinc-300">{x}</span></div>)}</div></div><div className="rounded-2xl border border-zinc-700 bg-zinc-950 p-5 shadow-2xl"><div className="rounded-xl border border-zinc-800 bg-zinc-900 p-5"><div className="mb-4 flex items-center justify-between"><span className="text-sm font-semibold text-white">Your workflow</span><span className="text-xs text-emerald-400">Ready to edit</span></div><div className="space-y-3">{['01 · Upload Media','02 · Upload Voiceover','03 · Original Script','04 · Word Timestamp Transcript','05 · Preview & Export'].map((x,i)=><div key={x} className="rounded-lg border border-zinc-800 bg-zinc-950 px-3 py-3"><div className="flex items-center gap-3"><span className="flex h-7 w-7 items-center justify-center rounded-full bg-amber-500 text-xs font-bold text-zinc-950">{i+1}</span><p className="text-sm text-zinc-300">{x}</p></div></div>)}</div></div></div></div></section>
    <MostPopularBlogs />
    <section className="mx-auto max-w-4xl px-4 py-20 text-center sm:px-6"><h2 className="text-3xl font-bold text-white sm:text-4xl">Ready to make the next video?</h2><p className="mx-auto mt-4 max-w-2xl text-zinc-400">Open the editor, upload your required data and let the tool make your work easier with the help of AI.</p><Link to="/editor" className="mt-7 inline-flex items-center gap-2 rounded-xl bg-amber-500 px-6 py-3.5 font-bold text-zinc-950 hover:bg-amber-400">Start editing <ArrowRight className="h-5 w-5" /></Link></section>
  </MarketingLayout>;
}

function Stat({title,text}:{title:string;text:string}){return <div className="rounded-xl border border-zinc-800 bg-zinc-950/70 p-4"><p className="font-semibold text-white">{title}</p><p className="mt-1 text-xs text-zinc-500">{text}</p></div>}
function FeatureCard({Icon,title,text}:{Icon:React.ElementType;title:string;text:string}){return <div className="rounded-2xl border border-zinc-800 bg-zinc-900/50 p-6 transition hover:-translate-y-0.5 hover:border-zinc-700"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-amber-500/10 text-amber-400"><Icon className="h-5 w-5"/></span><h3 className="mt-5 font-semibold text-white">{title}</h3><p className="mt-2 text-sm leading-6 text-zinc-500">{text}</p></div>}
